name: Generate README

on:
  schedule: [{cron: '0 2 * * *'}]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f script/requirements.txt ]; then pip install -r script/requirements.txt; fi
      - name: Generate README
        run: python script/readme.py
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -m "Update README"
          git push
      